repos:
  - repo: https://github.com/rubykatzen/baseline
    rev: v0.16.2 # x-release-please-version
    hooks:
      - id: yamllint
      - id: pymarkdown
      - id: ruff
      - id: tombi
      - id: shellcheck
      - id: actionlint
      - id: rubocop
