- id: yamllint
  name: yamllint
  language: script
  entry: hooks/yamllint.sh
  types: [yaml]
- id: pymarkdown
  name: pymarkdown
  language: script
  entry: hooks/pymarkdown.sh
  types: [markdown]
- id: ruff
  name: ruff
  language: script
  entry: hooks/ruff.sh
  types: [python]
- id: shellcheck
  name: shellcheck
  language: script
  entry: hooks/shellcheck.sh
  types: [shell]
- id: actionlint
  name: actionlint
  language: script
  entry: hooks/actionlint.sh
  files: ^\.github/workflows/.*\.ya?ml$
  pass_filenames: false
- id: rubocop
  name: rubocop
  language: script
  entry: hooks/rubocop.sh
  types: [ruby]
  args: [--force-exclusion]
- id: erb-lint
  name: erb-lint
  language: script
  entry: hooks/erb-lint.sh
  files: \.html(\+.*)?\.erb$
