fragments:
  config:
    path: release-please-config.json
    content: '"pull-request-title-pattern": "chore: release ${version}"'
  workflow-action:
    path: .github/workflows/release.yml
    content: "uses: googleapis/release-please-action"
  pull-request-title:
    path: .github/workflows/pr.yml
    content: "uses: amannn/action-semantic-pull-request"
