name: lint-rubocop
description: Lint Ruby files using Standard (via RuboCop) with baseline config. Requires rubocop and standard gems in project Gemfile.
runs:
  using: composite
  steps:
    - run: bundle exec rubocop --config "${{ github.action_path }}/../../../configs/rubocop.yml"
      shell: bash
