exclude:
  - 'vendor/**/*'
EnableDefaultLinters: true
linters:
  RequireInputAutocomplete:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_gem:
        rubykatzen-baseline: config/rubocop.yml
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
