extends: default
ignore: |
  vendor/
  node_modules/
  .bundle/
rules:
  empty-lines:
    max: 0
    max-start: 0
    max-end: 1
  trailing-spaces: enable
  line-length: disable
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false
