plugins:
  - rubocop-performance
  - rubocop-rails
  - standard-custom
inherit_from:
  - rubocop/standard.yml
  - rubocop/standard-performance.yml
  - rubocop/standard-rails.yml
  - rubocop/standard-custom.yml
AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
