name: Lint
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - run: python -m pip install yamllint pymarkdownlnt ruff
      - run: sudo apt-get update && sudo apt-get install -y shellcheck
      - run: |
          bash <(curl -sL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          sudo install actionlint /usr/local/bin/actionlint
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.5"
      - run: bundle install
        shell: bash
        env:
          BUNDLE_PATH: .bundle
      - uses: ./.github/actions/lint-yamllint
      - uses: ./.github/actions/lint-pymarkdown
      - uses: ./.github/actions/lint-ruff
      - uses: ./.github/actions/lint-shellcheck
      - uses: ./.github/actions/lint-actionlint
      - uses: ./.github/actions/lint-rubocop
      - uses: ./.github/actions/lint-erb-lint
