name: Notify Telegram release (shared)
on:
  workflow_call:
    inputs:
      telegram-chat-id:
        description: Telegram chat ID that receives notifications.
        required: true
        type: string
    secrets:
      telegram-bot-token:
        required: true
jobs:
  notify:
    if: >-
      github.event_name == 'release' &&
      github.event.action == 'published'
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - id: prepare
        uses: $/.github/actions/prepare-telegram-release-message
      - name: Send
        uses: $/.github/actions/send-telegram-message
        with:
          message: ${{ steps.prepare.outputs.message }}
          telegram-bot-token: ${{ secrets.telegram-bot-token }}
          telegram-chat-id: ${{ inputs.telegram-chat-id }}
          parse-mode: MarkdownV2
