name: Notify Telegram issue (shared)
on:
  workflow_call:
    secrets:
      TELEGRAM_BOT_TOKEN:
        required: true
      TELEGRAM_CHAT_ID:
        required: true
jobs:
  notify-closed:
    if: >-
      github.event_name == 'issues' &&
      github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - id: prepare
        uses: $/.github/actions/prepare-telegram-issue-message
      - name: Send
        uses: $/.github/actions/send-telegram-message
        with:
          message: ${{ steps.prepare.outputs.message }}
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          parse-mode: MarkdownV2
