name: pymarkdown
on:
  workflow_call:
jobs:
  pymarkdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          repository: dupmachine/workflows
          path: .linters
      - run: pip install pymarkdownlnt
      - run: pymarkdown --config .linters/configs/pymarkdown.json scan .
