name: Test
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: python3 -m pip install pyyaml identify
      - run: python3 -m unittest discover -s test -v
